# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e28e2428c4a87255fa4de9fe402967a0e9f3f14bb0f4b207affc8a571dc96ae69bd7b02053e88833cdeac73a3aeb9f005e14854914d98dbd7f50ac0fd94b2d4

test:
  secret_key_base: 530767736fcf8fc0b8b230e7f4524eba8469d07a10c7611154594891239b9d4790e5b5ddd00f414ed3017e642c7da966f1d8dee93ad66db6c1fb0bd1a653c1e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
